---
name: On Pull Request checks
on:
  pull_request:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
    name: On Pull Request checks
    timeout-minutes: 30
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - name: Run Upgrade utility
        env:
          FOLDER_PATH: ~/repo
          GITHUB_USER: $GITHIB_ACTOR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          ls
          mvn clean install
