---
name: Execute upgrade utility
on:
  pull_request:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
    name: On Pull Request checks
    timeout-minutes: 30
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - uses: actions/checkout@v2
      - name: Build project
        env:
          FOLDER_PATH: ~/repo
          GITHUB_USER: $GITHIB_ACTOR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          ls
          mvn clean install
          echo $GITHUB_ACTION
      - name: Open Issue
        id: create-issue
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: rohitmehra86
      - name: Send custom JSON data to Slack workflow
        id: slack
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "text": "Need to work on the <${{ steps.create-issue.outputs.url }}|issue",
              "attachments": [
                {
                  "pretext": "Need to work",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Open"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
