---
name: Execute upgrade utility
on:
  pull_request:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
    name: On Pull Request checks
    timeout-minutes: 30
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
      - uses: actions/checkout@v2
      - name: Build project
        env:
          FOLDER_PATH: ~/repo
          GITHUB_USER: $GITHIB_ACTOR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          ls
          mvn clean install
      - name: Open Issue
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: mehr.rohit86
