name: Release

on:
  push:
    branches:
      - master

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
      - name: release
        run: npx semantic-release